force-app/main/default/objects/Knowledge__kav/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Question for FAQ</description>
    <label>Question</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/KnowledgeController.cls
public with sharing class KnowledgeController {
    public KnowledgeController() {

    }
    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> findArticles(String searchKey){
        if(searchKey==''){
            return null;
        }
        String key = '%' + searchKey + '%';
        return [
            SELECT Answer__c,Question__c,Title FROM Knowledge__kav WHERE Title LIKE:key
        ];
    }
    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getAllArticles(){        
        return [
            SELECT Answer__c,Title FROM Knowledge__kav
        ];
    }
    @AuraEnabled(cacheable=true)
    public static Integer getNum(){        
        return [SELECT count() FROM Knowledge__kav];
    }
}